-- 健身卡配置表
CREATE TABLE IF NOT EXISTS `gym_card` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '卡名',
  `type` VARCHAR(20) NOT NULL COMMENT 'VISIT/MONTHLY/YEARLY',
  `price` DECIMAL(10,2) NOT NULL COMMENT '价格',
  `duration` INT NOT NULL COMMENT '有效期天数',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '描述',
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/INACTIVE',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='健身卡配置';

-- 会员健身卡持有表
CREATE TABLE IF NOT EXISTS `gym_membership` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '会员ID',
  `gym_card_id` BIGINT NOT NULL COMMENT '关联健身卡ID',
  `start_date` DATE NOT NULL COMMENT '生效日期',
  `end_date` DATE NOT NULL COMMENT '到期日期',
  `remaining_visits` INT DEFAULT NULL COMMENT '剩余次数(次卡)',
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/EXPIRED/USED_UP',
  `paid_amount` DECIMAL(10,2) NOT NULL COMMENT '支付金额',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_gym_card_id` (`gym_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员健身卡';
