CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    real_name VARCHAR(64),
    role VARCHAR(32) NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(128),
    gender VARCHAR(16),
    birthday VARCHAR(32),
    avatar VARCHAR(255),
    remark VARCHAR(500),
    create_time DATETIME,
    update_time DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE sys_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS phone VARCHAR(32);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS email VARCHAR(128);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS gender VARCHAR(16);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS birthday VARCHAR(32);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS avatar VARCHAR(255);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS remark VARCHAR(500);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS update_time DATETIME;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS deleted TINYINT DEFAULT 0;
